UniversityManagementSystemWebApp/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult TimePicker()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TimePicker(Timepicker timepicker)
        {
            //timepicker.Time = TimeSpan.FromDays(1);
            return View();
        }
	}
}

UniversityManagementSystemWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Script", required: false)
</body>
</html>

UniversityManagementSystemWebApp/Views/Shared/_MyLayout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap Template</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../Content/cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="../../Content/mdbootstrap.com/previews/docs/latest/css/bootstrap.min.css">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="../../Content/mdbootstrap.com/previews/docs/latest/css/mdb.min.css">
    @*@RenderSection("head", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="fixed-sn light-blue-skin">
    <header>
        <!-- Sidebar navigation -->
        <div id="slide-out" class="side-nav sn-bg-4 fixed">
            <ul class="custom-scrollbar">
                <!-- Logo -->
                <li>
                    <div class="logo-wrapper waves-light">
                        <a href="#"><img src="../../Content/imac.png" class="img-fluid flex-center"></a>
                    </div>
                </li>
                <!--/. Logo -->
                <!--Social-->
                <li>
                    <ul class="social">
                        <li><a href="https://www.facebook.com/" class="icons-sm fb-ic"><i class="fa fa-facebook"> </i></a></li>
                        <li><a href="https://www.pinterest.com" class="icons-sm pin-ic"><i class="fa fa-pinterest"> </i></a></li>
                        <li><a href="https://plus.google.com" class="icons-sm gplus-ic"><i class="fa fa-google-plus"> </i></a></li>
                        <li><a href="https://twitter.com/" class="icons-sm tw-ic"><i class="fa fa-twitter"> </i></a></li>
                    </ul>
                </li>
                <!--/Social-->
                <!--Search Form-->
                <li>
                    <form class="search-form" role="search">
                        <div class="form-group md-form mt-0 pt-1 waves-light">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                    </form>
                </li>
                <!--/.Search Form-->
                <!-- Side navigation links -->
                <li>
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-chevron-right"></i> Department<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href=@Url.Action("Save","Department") class="waves-effect">Save Department</a>
                                    </li>
                                    <li>
                                        <a href=@Url.Action("ViewAll","ViewAllDepartment") class="waves-effect">View Department</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-chevron-right"></i> Course<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href=@Url.Action("Save","Course")  class=" waves-effect">Save Course</a>
                                    </li>
                                    <li><a href="#" class="waves-effect"> Unassign Courses</a></li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-chevron-right"></i> Teacher<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href=@Url.Action("Save","Teacher") class="waves-effect">Save Teacher</a>
                                    </li>
                                    <li>
                                        <a href=@Url.Action("CourseAssign","CourseAssign") class="waves-effect">Course Assign to Teacher</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-chevron-right"></i> Student<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href=@Url.Action("Save","Student") class="waves-effect">Register Student</a>
                                    </li>
                                    <li>
                                        <a href=@Url.Action("Enroll","EnrollCourse") class="waves-effect">Enroll in a course</a>
                                    </li>
                                    <li>
                                        <a href=@Url.Action("Save","StudentResult") class="waves-effect">Save Student Result</a>
                                    </li>
                                    <li>
                                        <a href=@Url.Action("ViewResult","ViewResult") class="waves-effect">View Result</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-chevron-right"></i> Class Room<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href=@Url.Action("Save","AllocateCllassroom") class="waves-effect">Allocate Class Room</a>
                                    </li>
                                    <li>
                                        <a href=@Url.Action("ClassSchedule","AllocateCllassroom") class="waves-effect">View Class Schedule</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Unallocate class rooms</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-hand-pointer-o"></i> Instruction<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="#" class="waves-effect">For bloggers</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">For authors</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-eye"></i> About<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="#" class="waves-effect">Introduction</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Monthly meetings</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-envelope-o"></i> Contact me<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <!--/. Side navigation links -->
            </ul>
            <div class="sidenav-bg mask-strong"></div>
        </div>
        <!--/. Sidebar navigation -->
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-toggleable-md navbar-expand-lg scrolling-navbar double-nav">
            <!-- SideNav slide-out button -->
            <div class="float-left">
                <a href="#" data-activates="slide-out" class="button-collapse"><i class="fa fa-bars"></i></a>
            </div>
            <!-- Breadcrumb-->
            <div class="breadcrumb-dn mr-auto">
                <p>University Managerment System</p>
            </div>
            <ul class="nav navbar-nav nav-flex-icons ml-auto">
                <li class="nav-item">
                    <a class="nav-link"><i class="fa fa-envelope"></i> <span class="clearfix d-none d-sm-inline-block">Contact</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fa fa-comments-o"></i> <span class="clearfix d-none d-sm-inline-block">Support</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fa fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Account</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.Navbar -->
    </header>
    <!--/.Double navigation-->
    <!--Main Layout-->
    <main>
        <div class="container-fluid mt-5">
            @RenderBody()
        </div>
    </main>
    <!--Main Layout-->
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/jquery-3.3.1.min.js"></script>
    <!-- Tooltips -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/mdb.min.js"></script>
<script>

    // SideNav Initialization
    $(".button-collapse").sideNav();

</script>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)*@
</body>
</html>