UniversityManagementSystemWebApp/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityManagementSystemWebApp.Models
{
    public class Course
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Pleasee enter you Code")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Code must be 5 character long")]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
        [Required(ErrorMessage = "Pleasee enter you number")]
        [Range(0.5, 5, ErrorMessage = "Enter number between 0.5 to 5")]
        public float Credit { get; set; }
        public string Descrition { get; set; }
        [Required]
        [Display (Name = "Department")]
        public int DepartmentId { get; set; }
        [Required]
        [Display(Name = "Semester")]
        public int SemesterId { get; set; }
    }
}

UniversityManagementSystemWebApp/Models/CourseAssign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models
{
    public class CourseAssign
    {
        public int Id { get; set; }
        [Required]
        [Display (Name = "Department")]
        public int DepartmentId { get; set; }
        [Required]
        [Display(Name = "Teacher")]
        public int TeacherId { get; set; }
        [Required]
        [Display(Name = "Course Code")]
        public int CourseCode { get; set; }
    }
}

UniversityManagementSystemWebApp/Models/View Model/CourseAssignViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models.View_Model
{
    public class CourseAssignViewModel
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public float CreditToken { get; set; }
        public float RemainingCredit { get; set; }
        public int CourseId { get; set; }
        public string CourseCode { get; set; }
        public string Name { get; set; }
        public float Credit { get; set; }
    }
}

UniversityManagementSystemWebApp/Controllers/CourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.View_Model;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class CourseAssignController : Controller
    {
        //
        // GET: /CourseAssign/
        private CourseAssignManager courseAssignManager;
        private TeacherManager teacherManager;
        private DepartmentManager departmentManager;
        private CourseManager courseManager;
        public CourseAssignController()
        {
            courseAssignManager=new CourseAssignManager();
            teacherManager=new TeacherManager();
            departmentManager=new DepartmentManager();
            courseManager=new CourseManager();
        }


        [HttpGet]
        public ActionResult CourseAssign()
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();

            return View();
        }
        [HttpPost]
        public ActionResult CourseAssign(CourseAssign courseAssign)
        {
            if (ModelState.IsValid)
            {
                string message = courseAssignManager.Save(courseAssign);
                ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
                ViewBag.Message = message;
                ModelState.Clear();
                return View();
            }
            else
            {
                ViewBag.Message = "Model is not valid";
                return View();
            }
        }
        public JsonResult GetDepartmentId(int departmentId)
        {
            List<CourseAssignViewModel> courseAssignView= courseAssignManager.GetTeachersByDepartmentId(departmentId);
            return Json(courseAssignView);
        }

        public JsonResult GetDepartmentIdByCourse(int departmentId)
        {
            List<CourseAssignViewModel> courseAssignView1 = courseAssignManager.GetCoursesByDepartmentId(departmentId);
            return Json(courseAssignView1);
        }
        public JsonResult GetCourseId(int courseId)
        {
            List<Course> courseAssignViews = courseAssignManager.GetCourseCode(courseId);
            return Json(courseAssignViews);
        }
        public JsonResult GetTeacherId(int teacherId)
        {
            List<Teacher> courseAssignViewsTeachers = teacherManager.GetTeacherId(teacherId);
            return Json(courseAssignViewsTeachers);
        }

        public ActionResult CourseView()
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            return View();
        }

        public JsonResult GetDepartmentByCourseView(int departmentId)
        {
            List<CourseStaticViewModel> courseModel = courseAssignManager.GetCourseInfo(departmentId);
            return Json(courseModel);
        }
	}
}

UniversityManagementSystemWebApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/

        private CourseManager courseManager;
        private DepartmentManager departmentManager;
        private SemesterManager semesterManager;
        public CourseController()
        {
            courseManager=new CourseManager();   
            departmentManager=new DepartmentManager();
            semesterManager=new SemesterManager();
        }
        //public List<Department> Departments()
        //{
        //    List<Department> departments = courseManager.GetDepartments();

        //}
        [HttpGet]
        public ActionResult Save()
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            ViewBag.Semesters = semesterManager.GetSelectListItemsForSemesterDropdown();
            return View();
        }
        [HttpPost]
        public ActionResult Save(Course course)
        {

            if (ModelState.IsValid)
            {               
                string message = courseManager.Save(course);
                ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
                ViewBag.Semesters = semesterManager.GetSelectListItemsForSemesterDropdown();
                ViewBag.Message = message;
                ModelState.Clear();
                return View();
            }
            else
            {
                ViewBag.Message = "Model state is Invalide";
                return View();
            }

        }
	}
}

UniversityManagementSystemWebApp/Views/CourseAssign/CourseAssign.cshtml
@model UniversityManagementSystemWebApp.Models.CourseAssign
@{
    //Layout = null;
    //Layout = "~/Views/Shared/_MyLayout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CourseAssign</title>
    <style>
        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
<div>
    @using (Html.BeginForm(null, null, FormMethod.Post))
    {
        <fieldset>
            <legend>Course Assign to Teacher</legend>
            <table>
                <tr>
                    <td>@Html.LabelFor(x=>x.DepartmentId)</td>
                    <td>
                        @Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "Value", "Text"))
                        @Html.ValidationMessageFor(x=>x.DepartmentId)
                    </td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(x=>x.TeacherId)</td>
                    <td><select id="TeacherId" name="TeacherId" class="TeacherId">
                            <option value="">--Select--</option>
                        </select>
                        @Html.ValidationMessageFor(x => x.TeacherId)
                    </td>
                </tr>
                <tr>
                    <td>@Html.Label("CreditTaken")</td>
                    <td>
                        @Html.TextBox("CreditTaken")
                    </td>
                </tr>
                <tr>
                    <td>@Html.Label("RemainingCredit")</td>
                    <td>@Html.TextBox("RemainingCredit")</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(x=>x.CourseCode)</td>
                    <td>
                        <select id="CourseCode" name="CourseCode" class="CourseCode">
                            <option value="">--Select--</option>
                        </select>
                        
                        @Html.ValidationMessageFor(x => x.CourseCode)
                    </td>
                </tr>
                <tr>
                    <td>@Html.Label("Name")</td>
                    <td>@Html.TextBox("Name")</td>
                </tr>
                <tr>
                    <td>@Html.Label("Credit")</td>
                    <td>@Html.TextBox("Credit")</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Assign"/></td>
                </tr>
            </table>
            @if (ViewBag.Message != null)
            {
                <p>@ViewBag.Message</p>
            }
        </fieldset>
    }
</div>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $("#TeacherId").prop('disabled', true);
        $("#CourseCode").prop('disabled', true);
        $("#CreditTaken").prop('disabled', true);
        $("#RemainingCredit").prop('disabled', true);
        $("#Name").prop('disabled', true);
        $("#Credit").prop('disabled', true);

        $("#DepartmentId").change(function () {
            var deptId = $("#DepartmentId").val();
            var json =
            {
                departmentId: deptId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetDepartmentId", "CourseAssign")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $("#TeacherId").find("option").remove();
                    //$("#TeacherId").empty();
                    //$("#CourseCode").empty();
                    $("#TeacherId").append('<option value="">--Select---</option');
                    //$("#CourseCode").append('<option value="">--Select---</option');
                    $.each(data, function (key, value) {
                        $("#TeacherId").prop('disabled', false);
                        $("#CourseCode").prop('disabled', false);
                        $("#TeacherId").append('<option value=' + value.Id + '>' + value.Name + '</option');
                    });
                }
            });

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetDepartmentIdByCourse", "CourseAssign")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $("#CourseCode").find("option").remove();
                    //$("#TeacherId").empty();
                    //$("#CourseCode").empty();
                    //$("#TeacherId").append('<option value="">--Select---</option');
                    $("#CourseCode").append('<option value="">--Select---</option');
                    $.each(data, function (key, value) {
                        $("#TeacherId").prop('disabled', false);
                        $("#CourseCode").prop('disabled', false);
                        $("#CourseCode").append('<option value=' + value.CourseId + '>' + value.CourseCode + '</option>');
                    });
                }
            });
        });

        $("#TeacherId").change(function () {

            var tecId = $("#TeacherId").val();
            var json = { teacherId: tecId };

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeacherId", "CourseAssign")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $.each(data, function (key, value) {
                        //$("#CreditTaken").prop('disabled', false);
                        //$("#RemainingCredit").prop('disabled', false);
                        var creditTaken = value.CreditToken;
                        var remainingCredit = value.ReminingCredit;
                        $("#CreditTaken").val(creditTaken);
                        $("#RemainingCredit").val(remainingCredit);
                        
                    });


                    //var creditTakenTobeTaken = data.CreditTobeTaken;
                    //var remainingCredit = (data.CreditTaken);
                    //var creditT = creditTakenTobeTaken - remainingCredit;
                    //$("#CreditTobeTaken").val(creditTakenTobeTaken);
                    //$("#CreditTaken").val(creditT);


                }
            });
        });

        $("#CourseCode").change(function () {
            var couId = $("#CourseCode").val();
            //$("#studentId").empty();
            var json =
            {
                CourseId: couId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseId", "CourseAssign")',
                //url: '/Student/GetStudentsByDepartmentId',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $.each(data, function (key, value) {
                        var name = value.Name;
                        var credit = value.Credit;
                        $("#Name").val(name);
                        $("#Credit").val(credit);
                    });
                }
            });
        });

    });
</script>
</body>
</html>

UniversityManagementSystemWebApp/Views/CourseAssign/CourseView.cshtml
@{
    //Layout = null;
    //Layout = "~/Views/Shared/_MyLayout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CourseView</title>
</head>
<body>
    <div>
        <fieldset>
            <legend>View Course Statics</legend>
            @using (Html.BeginForm(null, null, FormMethod.Post))
            {
                <table>
                    <tr>
                        <td>@Html.Label("DepartmentId")</td>
                        <td>@Html.DropDownList("DepartmentId", new SelectList(ViewBag.Departments, "Value", "Text"))</td>
                    </tr>
                </table>
                <h1>Course Information</h1>
                <table border="1">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Name/Title</th>
                            <th>Semester</th>
                            <th>Assigned To</th>
                        </tr>
                    </thead>
                    <tbody id="courseInfo"></tbody>

                </table>               
            }
        </fieldset>
    </div>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#DepartmentId").change(function () {
                var deptId = $("#DepartmentId").val();
                var json =
                {
                    departmentId: deptId
                };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetDepartmentByCourseView", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $("#courseInfo").empty();
                        $.each(data, function (key, value) {
                            $("#courseInfo").append('<tr> <td>' + value.Code + '</td> <td>' + value.Name + '</td> <td>' + value.Semester + '</td> <td>' + value.Teacher + '</td> </tr>');
                        });
                    }
                });
            });
        });
    </script>
</body>
</html>