UniversityManagementSystemWebApp/Models/ClassSchedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models
{
    public class ClassSchedule
    {
        public int CourseId { get; set; }
        [Required]
        [Display (Name = "Department")]
        public int DepartmentId { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string Schedule { get; set; }
    }
}

UniversityManagementSystemWebApp/Controllers/AllocateCllassroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.View_Model;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class AllocateCllassroomController : Controller
    {
        private DepartmentManager departmentManager;
        private CourseManager courseManager;
        private RoomManager roomManager;
        private DayManager dayManager;
        private AllocateClassroomsManager allocateClassroomsManager;

        public AllocateCllassroomController()
        {
            departmentManager=new DepartmentManager();
            courseManager=new CourseManager();
            roomManager=new RoomManager();
            dayManager=new DayManager();
            allocateClassroomsManager=new AllocateClassroomsManager();
        }
        //
        // GET: /AllocateCllassroom/
        [HttpGet]
        public ActionResult Save()
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            ViewBag.Rooms = roomManager.GetAllRoomCodeList();
            ViewBag.Days = dayManager.GetAllDayList();
            return View();
        }
        [HttpPost]

        public ActionResult Save(AllocateClassrooms allocateClassrooms)
        {
            //if (ModelState.IsValid)
            //{
                string message = allocateClassroomsManager.Save(allocateClassrooms);
                ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
                ViewBag.Rooms = roomManager.GetAllRoomCodeList();
                ViewBag.Days = dayManager.GetAllDayList();
                ViewBag.Message = message;
                ModelState.Clear();
                return View();
            //}
            //else
            //{
            //    ViewBag.Message = "Model is not valid";
            //    return View();
            //}
        }
        public JsonResult GetCourseByDepartmentId(int departmentId)
        {
            List<Course> courseList = courseManager.GetCoursesById(departmentId);
            return Json(courseList);
        }

        [HttpGet]
        public ActionResult ClassSchedule()
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            return View();
        }

        [HttpPost]
        public ActionResult ClassSchedule(ClassSchedule classSchedule)
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            return View();
        }
       
	}
}

UniversityManagementSystemWebApp/Views/AllocateCllassroom/ClassSchedule.cshtml
@model UniversityManagementSystemWebApp.Models.ClassSchedule
@{
    Layout = null;
    //Layout = "~/Views/Shared/_MyLayout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClassSchedule</title>
</head>
<body>
<div>
    @using (Html.BeginForm(null, null, FormMethod.Post))
    {
        <table>
            <tr>
                <td>@Html.LabelFor(x => x.DepartmentId)</td>
                <td>@Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "Value", "Text"),new {@class="form-control"})</td>
            </tr>
        </table>

        <table border="1">
            <thead>
            <tr>
                <th>Course Code</th>
                <th>Name</th>
                <th>Schedule Info</th>
            </tr>
            </thead>
            <tbody id="ScheduleInfo"></tbody>
        </table>
    }
</div>
</body>
</html>

UniversityManagementSystemWebApp/Views/AllocateCllassroom/Save.cshtml
@model UniversityManagementSystemWebApp.Models.AllocateClassrooms
@{
    Layout = null;
    //Layout = "~/Views/Shared/_MyLayout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save</title>
    <link href="~/Content/mdtimepicker.css" rel="stylesheet" />
</head>
<body>
<div>
    <fieldset>
        <legend>Allocate Classrooms</legend>
        @using (Html.BeginForm(null, null, FormMethod.Post))
        {
            <table>
                <tr>
                    <td>@Html.Label("DepartmentId")</td>
                    <td>@Html.DropDownList("DepartmentId", new SelectList(ViewBag.Departments, "Value", "Text"))</td>
                </tr>
                <tr>
                    <td>@Html.Label("CourseId")</td>
                    <td>
                        <select id="CourseId" name="CourseId" class="CourseId">
                            <option value="">--Select--</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>@Html.Label("Room No")</td>
                    <td>@Html.DropDownList("RoomId", new SelectList(ViewBag.Rooms, "Value", "Text"))</td>
                </tr>
                <tr>
                    <td>@Html.Label("Day")</td>
                    <td>@Html.DropDownList("DayId", new SelectList(ViewBag.Days, "Value", "Text"))</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(x=>x.FromTime)</td>
                    <td>@Html.TextBoxFor(x=>x.FromTime)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(x => x.ToTime)</td>
                    <td>@Html.TextBoxFor(x => x.ToTime)</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" id="Allocate"/></td>
                </tr>
            </table>
        }
        @if (ViewBag.Message != null)
        {
            <h3>@ViewBag.Message</h3>
        }
    </fieldset>
</div>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/mdtimepicker.js"></script>
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
<script>
    $(document).ready(function() {
        $("#DepartmentId").change(function() {
            var deptId = $("#DepartmentId").val();
            var json =
            {
                departmentId: deptId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseByDepartmentId", "AllocateCllassroom")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $.each(data, function (key, value) {                      
                        $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');
                    });
                }
            });
        });

        $('#FromTime').mdtimepicker();
        $('#ToTime').mdtimepicker();
    });
</script>
</body>
</html>