UniversityManagementSystemWebApp/Models/EnrollCourse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models
{
    public class EnrollCourse
    {
        public int Id { get; set; }
        [Required]
        public int  RegistrationNo{ get; set; }
        [Required]
        [Display(Name = "Course")]
        public int  CourseId{ get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime  Date{ get; set; }
    }
}

UniversityManagementSystemWebApp/Models/View Model/EnrollViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models.View_Model
{
    public class EnrollViewModel
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string CourseName { get; set; }

    }
}

UniversityManagementSystemWebApp/Controllers/EnrollCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.View_Model;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class EnrollCourseController : Controller
    {
        //
        // GET: /EnrollCourse/
        private DepartmentManager departmentManager;
        private CourseManager courseManager;
        private StudentManager studentManager;
        private EnrollManager enrollManager;

        public EnrollCourseController()
        {
            departmentManager=new DepartmentManager();
            courseManager=new CourseManager();
            studentManager=new StudentManager();
            enrollManager=new EnrollManager();
        }
        [HttpGet]
        public ActionResult Enroll()
        {
            ViewBag.StudentRegNo = studentManager.GetSelectListItemsForDropdown();
            ViewBag.Courses = courseManager.GetAllCourse();
            return View();
        }

        [HttpPost]
        public ActionResult Enroll(EnrollCourse enrollCourse)
        {
            if (ModelState.IsValid)
            {
                string message = enrollManager.Save(enrollCourse);
                ViewBag.StudentRegNo = studentManager.GetSelectListItemsForDropdown();
                ViewBag.Courses = courseManager.GetAllCourse();
                ViewBag.Message = message;
                ModelState.Clear();
                return View();
            }
            else
            {
                ViewBag.Message = "Model Is not Valid";
                return View();
            }
        }
        public JsonResult RegistrationNo(int registrationId)
        {
            List<StudentResultViewModel> enrollViewModels = studentManager.GetRegNoByStudentInfo(registrationId);
            return Json(enrollViewModels);
        }
	}
}

UniversityManagementSystemWebApp/Views/EnrollCourse/Enroll.cshtml
@model UniversityManagementSystemWebApp.Models.EnrollCourse
@{
    //Layout = null;
    //Layout = "~/Views/Shared/_MyLayout1.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Enroll</title>
    <style>
        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
<div>
    <fieldset>
        <legend>Enroll In a Course</legend>
        @using (Html.BeginForm(null, null, FormMethod.Post))
        {
            <table>
                <tr>
                    <td>@Html.LabelFor(x => x.RegistrationNo)</td>
                    <td>
                        @Html.DropDownListFor(x => x.RegistrationNo, new SelectList(ViewBag.StudentRegNo, "Value", "Text"))
                        @Html.ValidationMessageFor(x => x.RegistrationNo)
                    </td>

                </tr>
                <tr>
                    <td>@Html.Label("Name")</td>
                    <td>
                        @Html.TextBox("Name")
                    </td>

                </tr>
                <tr>
                    <td>@Html.Label("Email")</td>
                    <td>
                        @Html.TextBox("Email")
                    </td>

                </tr>
                <tr>
                    <td>@Html.Label("Department")</td>
                    <td>
                        @Html.TextBox("DepartmentId")
                    </td>

                </tr>
                <tr>
                    <td>@Html.LabelFor(x => x.CourseId)</td>
                    <td>
                        @Html.DropDownListFor(x => x.CourseId, new SelectList(ViewBag.Courses,"Value","Text"), new { style = "width:165px;" })
                        @Html.ValidationMessageFor(x => x.CourseId)
                    </td>

                </tr>
                <tr>
                    <td>@Html.Label("Date")</td>
                    <td>
                        <input type="text" id="Date" name="Date" value="@DateTime.Now.ToShortDateString()"/>
                        @Html.ValidationMessageFor(x => x.Date)
                    </td>

                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Enroll"/></td>
                </tr>
            </table>
        }
        @if (ViewBag.Message != null)
        {
            <p>@ViewBag.Message</p>
        }
    </fieldset>
</div>

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $("#Name").prop('disabled', true);
        $("#Email").prop('disabled', true);
        $("#DepartmentId").prop('disabled', true);
        $("#Date").datepicker({ dateFormat: "dd-mm-yy" });
        $("#Date").on("change", function () {
            var selected = $(this).val();
            $("#Date").val(selected);
        });
        $("#RegistrationNo").change(function() {
            var regId = $("#RegistrationNo").val();
            var json =
            {
                registrationId: regId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("RegistrationNo", "EnrollCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $.each(data, function (key, value) {
                        $("#Name").val(value.Name);
                        $("#Email").val(value.Email);
                        $("#DepartmentId").val(value.DepartmentName);
                    });
                }
            });
        });
    });
</script>
</body>
</html>